version: "3.8"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'test_app_development'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3309:3306"
    volumes:
      - dbdata:/var/lib/mysql

  web:
    build: .
    # entrypoint: /app/docker-entrypoint.sh
    ports: 
      - "3001:3000"
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  dbdata:
